totals = [ ["HousePg", "Utilities", "Cell Phone Christina", ""],
["HousePg", "Utilities", "Cell Phone Gary", ""],
["HousePg", "Utilities", "Internet", ""],
["HousePg", "Utilities", "Wood", ""],
["HousePg", "Utilities", "Electricity", ""],
["HousePg", "Professional", "Prof. Fees (Gary)", ""],
["HousePg", "Professional", "Domain Name(s)", ""],
["HousePg", "Professional", "Prof. Development", ""],
["HousePg", "Professional", "Education", ""],
["HousePg", "House", "House Repairs", ""],
["HousePg", "House", "mortgage + prop. Tax", ""],
["HousePg", "House", "House Insurance", ""],
["HousePg", "House", "furniture", ""],
["HousePg", "Subscriptions", "YouTube Music", ""],
["HousePg", "Subscriptions", "Audible", ""],
["HousePg", "Subscriptions", "Disney+", ""],
["HousePg", "Subscriptions", "Amazon Prime", ""],
["HousePg", "Subscriptions", "costco membership", ""],
["HousePg", "Subscriptions", "Microsoft Office", ""],
["HousePg", "Subscriptions", "ExpressVPN", ""],
["HousePg", "Subscriptions", "1Password", ""],
["HousePg", "Subscriptions", "cricut", ""],
["DailyPg", "Food", "Fast Food", ""],
["DailyPg", "Food", "Groceries", ""],
["DailyPg", "Food", "Dining Out", ""],
["DailyPg", "Food", "Energy Drinks/Snacks", ""],
["DailyPg", "Clothing", "Gary Clothing", ""],
["DailyPg", "Clothing", "Christina Clothing", ""],
["DailyPg", "Clothing", "Child Clothing", ""],
["DailyPg", "Clothing", "Dry Cleaning", ""],
["DailyPg", "Clothing", "costumes", ""],
["DailyPg", "Grooming", "Beauty Products (soap, makeup, etc.)", ""],
["DailyPg", "Grooming", "Cleansing Products (shampoo, body wash, etc)", ""],
["DailyPg", "Grooming", "Teeth (toothbrush, toothpaste, etc)", ""],
["DailyPg", "Grooming", "Hair Cuts", ""],
["DailyPg", "Supplies", "Cleaning Supplies", ""],
["DailyPg", "Supplies", "Garden Supplies", ""],
["DailyPg", "Supplies", "Home Décor", ""],
["DailyPg", "Supplies", "Organization", ""],
["DailyPg", "Supplies", "General House Items", ""],
["DailyPg", "Supplies", "Tools", ""],
["DailyPg", "Supplies", "Electronics", ""],
["HealthPg", "Health", "Dental", ""],
["HealthPg", "Health", "OTC Drugs", ""],
["HealthPg", "Health", "Prescriptions", ""],
["HealthPg", "Health", "Supplements", ""],
["HealthPg", "Health", "Paramedical", ""],
["HealthPg", "Health", "Family Life Insurance", ""],
["HealthPg", "Health", "other", ""],
["HealthPg", "Health", "Therapy", ""],
["HealthPg", "Health", "Sexual Health", ""],
["DependentsPg", "Barney", "Preventitive Medical (vaccines, tick, etc)", ""],
["DependentsPg", "Barney", "Emergency Medical", ""],
["DependentsPg", "Barney", "Food", ""],
["DependentsPg", "Barney", "Treats", ""],
["DependentsPg", "Barney", "Toys", ""],
["DependentsPg", "Barney", "Daycare", ""],
["DependentsPg", "Barney", "Pet Insurance (trupanion)", ""],
["DependentsPg", "Barney", "grooming", ""],
["DependentsPg", "Children", "Childcare", ""],
["DependentsPg", "Children", "ExtraCurriculars", ""],
["DependentsPg", "Children", "Equipment", ""],
["DependentsPg", "Children", "Family Activities", ""],
["DependentsPg", "Children", "Babysitting", ""],
["DependentsPg", "Children", "Diapers etc (wipes, genie)", ""],
["DependentsPg", "Children", "Toys", ""],
["DependentsPg", "Children", "Formula", ""],
["DependentsPg", "Children", "baby supplies", ""],
["EntertainmentPg", "Sports", "Friday/Tuesday Hockey", ""],
["EntertainmentPg", "Sports", "AHG Hockey", ""],
["EntertainmentPg", "Sports", "Hockey Equipment", ""],
["EntertainmentPg", "Sports", "Pick-up Hockey", ""],
["EntertainmentPg", "Entertainment", "Books", ""],
["EntertainmentPg", "Entertainment", "Lottery", ""],
["EntertainmentPg", "Entertainment", "Dates", ""],
["EntertainmentPg", "Entertainment", "Concerts/Events", ""],
["EntertainmentPg", "Entertainment", "Substances", ""],
["EntertainmentPg", "Entertainment", "Hosting", ""],
["EntertainmentPg", "Entertainment", "Games", ""],
["EntertainmentPg", "Vacations", "Air Fare/public trans.", ""],
["EntertainmentPg", "Vacations", "Accommodations", ""],
["EntertainmentPg", "Vacations", "Alcohol", ""],
["EntertainmentPg", "Vacations", "Food", ""],
["EntertainmentPg", "Vacations", "Travel Insurance", ""],
["EntertainmentPg", "Vacations", "Souvenirs", ""],
["EntertainmentPg", "Vacations", "Rental Car", ""],
["EntertainmentPg", "Vacations", "Other", ""],
["EntertainmentPg", "Vacations", "gas", ""],
["EntertainmentPg", "Vacations", "Camping supplies", ""],
["EntertainmentPg", "Vacations", "Activities", ""],
["TransportPg", "Transportation", "Car cleaning", ""],
["TransportPg", "Transportation", "Gas/Fuel", ""],
["TransportPg", "Transportation", "Combined Car Insurance", ""],
["TransportPg", "Transportation", "Parking", ""],
["TransportPg", "Transportation", "Tolls", ""],
["TransportPg", "Transportation", "Licenses Renewals", ""],
["TransportPg", "Transportation", "Vehicle Maintenance", ""],
["TransportPg", "Transportation", "Vehicle Registration", ""],
["TransportPg", "Transportation", "Repairs", ""],
["TransportPg", "Transportation", "Vehicle inspections", ""],
["TransportPg", "Transportation", "Public Transport", ""],
["AccountsPg", "Debt", "Student Loans", ""],
["AccountsPg", "Debt", "Charitable Donations", ""],
["AccountsPg", "Savings", "RESP", ""],
["AccountsPg", "Savings", "Christina TFSA", ""],
["AccountsPg", "Savings", "Christina RRSP", ""],
["AccountsPg", "Savings", "Gary TFSA", ""],
["AccountsPg", "Savings", "Gary RRSP", ""],
["AccountsPg", "Savings", "Emerg. Fund", ""],
["AccountsPg", "Savings", "Business Investment", ""],
["AccountsPg", "Savings", "Accounting", ""],
["AccountsPg", "Accounts", "Christina Bank Fees", ""],
["AccountsPg", "Accounts", "Gary Bank Fees", ""],
["AccountsPg", "Accounts", "Mutual Bank Fees", ""],
["AccountsPg", "Accounts", "Gifts", ""],
["AccountsPg", "Accounts", "Accounting", ""],
["IncomePg", "Christina Income", "Taxable", ""],
["IncomePg", "Christina Income", "Non-Taxable", ""],
["IncomePg", "Christina Income", "CCB", ""],
["IncomePg", "Gary Income", "Taxable", ""],
["IncomePg", "Gary Income", "Non-Taxable", ""] ]
