totals = [ ["HousePg", "Utilities", "Cell Phone Christina",""],
["HousePg", "Utilities", "Cell Phone Gary",""],
["HousePg", "Utilities", "Internet",""],
["HousePg", "Utilities", "Wood",""],
["HousePg", "Utilities", "Electricity",""],
["HousePg", "Professional", "Prof. Fees (Gary)",""],
["HousePg", "Professional", "Domain Name(s)",""],
["HousePg", "Professional", "Prof. Development",""],
["HousePg", "Professional", "Education",""],
["HousePg", "House", "House Repairs",""],
["HousePg", "House", "mortgage + prop. Tax",""],
["HousePg", "House", "House Insurance",""],
["HousePg", "House", "furniture",""],
["HousePg", "Subscriptions", "YouTube Music",""],
["HousePg", "Subscriptions", "Audible",""],
["HousePg", "Subscriptions", "Disney+",""],
["HousePg", "Subscriptions", "Amazon Prime",""],
["HousePg", "Subscriptions", "costco membership",""],
["HousePg", "Subscriptions", "Microsoft Office",""],
["HousePg", "Subscriptions", "ExpressVPN",""],
["HousePg", "Subscriptions", "1Password",""],
["HousePg", "Subscriptions", "cricut",""],
["DailyPg", "Food", "Fast Food",""],
["DailyPg", "Food", "Groceries",""],
["DailyPg", "Food", "Dining Out",""],
["DailyPg", "Food", "Energy Drinks/Snacks",""],
["DailyPg", "Clothing", "Gary Clothing",""],
["DailyPg", "Clothing", "Christina Clothing",""],
["DailyPg", "Clothing", "Aurora Clothing",""],
["DailyPg", "Clothing", "Dry Cleaning",""],
["DailyPg", "Clothing", "costumes",""],
["DailyPg", "Toiletries", "Beauty Products (soap, makeup, etc.)",""],
["DailyPg", "Toiletries", "Cleansing Products (shampoo, body wash, etc)",""],
["DailyPg", "Toiletries", "Teeth (toothbrush, toothpaste, etc)",""],
["DailyPg", "Supplies", "Cleaning Supplies",""],
["DailyPg", "Supplies", "Garden Supplies",""],
["DailyPg", "Supplies", "Home Décor",""],
["DailyPg", "Supplies", "Organization",""],
["DailyPg", "Supplies", "General House Items",""],
["DailyPg", "Supplies", "Tools",""],
["DailyPg", "Supplies", "Electronics",""],
["HealthPg", "Health", "Dental",""], 
["HealthPg", "Health", "OTC Drugs",""], 
["HealthPg", "Health", "Prescriptions",""], 
["HealthPg", "Health", "Supplements",""], 
["HealthPg", "Health", "Paramedical",""], 
["HealthPg", "Health", "Family Life Insurance",""], 
["HealthPg", "Health", "other",""], 
["HealthPg", "Health", "Therapy",""], 
["HealthPg", "Misc", "Christina Bank Fees",""], 
["HealthPg", "Misc", "Gary Bank Fees",""], 
["HealthPg", "Misc", "Mutual Bank Fees",""], 
["HealthPg", "Misc", "Hair Cuts",""], 
["HealthPg", "Misc", "Gifts",""], 
["HealthPg", "Misc", "Accounting",""], 
["DependentsPg", "Barney", "Preventitive Medical (vaccines, tick, etc)",""], 
["DependentsPg", "Barney", "Emergency Medical",""], 
["DependentsPg", "Barney", "Food",""], 
["DependentsPg", "Barney", "Treats",""], 
["DependentsPg", "Barney", "Toys",""], 
["DependentsPg", "Barney", "Daycare",""], 
["DependentsPg", "Barney", "Pet Insurance (trupanion)",""], 
["DependentsPg", "Barney", "grooming",""], 
["DependentsPg", "Aurora", "Childcare",""], 
["DependentsPg", "Aurora", "Swimming",""], 
["DependentsPg", "Aurora", "Family Activities",""], 
["DependentsPg", "Aurora", "Babysitting",""], 
["DependentsPg", "Aurora", "Diapers etc (wipes, genie)",""], 
["DependentsPg", "Aurora", "Toys",""], 
["DependentsPg", "Aurora", "baby supplies",""], 
["EntertainmentPg", "Sports", "Friday/Tuesday Hockey",""], 
["EntertainmentPg", "Sports", "AHG Hockey",""], 
["EntertainmentPg", "Sports", "Hockey Equipment",""], 
["EntertainmentPg", "Sports", "Pick-up Hockey",""], 
["EntertainmentPg", "Entertainment", "Books",""], 
["EntertainmentPg", "Entertainment", "Lottery",""], 
["EntertainmentPg", "Entertainment", "Dates",""], 
["EntertainmentPg", "Entertainment", "Concerts/Events",""], 
["EntertainmentPg", "Entertainment", "Alcohol",""], 
["EntertainmentPg", "Entertainment", "Hosting",""], 
["EntertainmentPg", "Entertainment", "Board Games",""], 
["EntertainmentPg", "Entertainment", "Weed",""], 
["EntertainmentPg", "Vacations", "Air Fare/public trans.",""], 
["EntertainmentPg", "Vacations", "Accommodations",""], 
["EntertainmentPg", "Vacations", "Alcohol",""], 
["EntertainmentPg", "Vacations", "Food",""], 
["EntertainmentPg", "Vacations", "Travel Insurance",""], 
["EntertainmentPg", "Vacations", "Souvenirs",""], 
["EntertainmentPg", "Vacations", "Rental Car",""], 
["EntertainmentPg", "Vacations", "Other",""], 
["EntertainmentPg", "Vacations", "gas",""], 
["EntertainmentPg", "Vacations", "Camping supplies",""], 
["EntertainmentPg", "Vacations", "Activities",""], 
["TransportationPg", "Transportation", "Car cleaning",""], 
["TransportationPg", "Transportation", "Gas/Fuel",""], 
["TransportationPg", "Transportation", "Combined Car Insurance",""], 
["TransportationPg", "Transportation", "Parking",""], 
["TransportationPg", "Transportation", "Tolls",""], 
["TransportationPg", "Transportation", "Licenses Renewals",""], 
["TransportationPg", "Transportation", "Vehicle Maintenance",""], 
["TransportationPg", "Transportation", "Vehicle Registration",""], 
["TransportationPg", "Transportation", "Repairs",""], 
["TransportationPg", "Transportation", "Vehicle inspections",""], 
["TransportationPg", "Transportation", "Public Transport",""], 
["MoneyPg", "Debt", "LOC Payments",""], 
["MoneyPg", "Debt", "Student Loans",""], 
["MoneyPg", "Debt", "Charitable Donations",""], 
["MoneyPg", "Savings", "Aurora RESP",""], 
["MoneyPg", "Savings", "Christina TFSA",""], 
["MoneyPg", "Savings", "Christina RRSP",""], 
["MoneyPg", "Savings", "Gary TFSA",""], 
["MoneyPg", "Savings", "Gary RRSP",""], 
["MoneyPg", "Savings", "Emerg. Fund",""], 
["MoneyPg", "Savings", "Business Investment",""], 
["MoneyPg", "Christina Income", "Gross Income",""], 
["MoneyPg", "Christina Income", "Other Income",""], 
["MoneyPg", "Christina Income", "Prof. Fees",""], 
["MoneyPg", "Christina Income", "Pension",""], 
["MoneyPg", "Christina Income", "Health/Denta Insur.",""], 
["MoneyPg", "Christina Income", "Life Insurance",""], 
["MoneyPg", "Christina Income", "Income Tax",""], 
["MoneyPg", "Christina Income", "EI",""], 
["MoneyPg", "Christina Income", "CPP",""], 
["MoneyPg", "Christina Income", "Union Dues",""], 
["MoneyPg", "Christina Income", "IWK Donation",""], 
["MoneyPg", "Christina Income", "Canadian Child Benefit",""], 
["MoneyPg", "Gary Income", "Gross Income",""], 
["MoneyPg", "Gary Income", "Health/Dental Insur.",""], 
["MoneyPg", "Gary Income", "Life Insurance",""], 
["MoneyPg", "Gary Income", "Income Tax",""], 
["MoneyPg", "Gary Income", "EI",""], 
["MoneyPg", "Gary Income", "CPP",""], 
["MoneyPg", "Gary Income", "Taxable Income",""], 
["MoneyPg", "Gary Income", "Non Taxable Income",""] ]

