totals = [ 
["", "", ""],
["tblUtilities", "Cell Phone Christina", ""],
["tblUtilities", "Cell Phone Gary", ""],
["tblUtilities", "Internet", ""],
["tblUtilities", "Wood", ""],
["tblUtilities", "Electricity", ""],
["", "", ""],
["tblProfessional", "Prof. Fees (Gary)", ""],
["tblProfessional", "Domain Name(s)", ""],
["tblProfessional", "Prof. Development", ""],
["tblProfessional", "Education", ""],
["", "", ""],
["tblHouse", "House Repairs", ""],
["tblHouse", "mortgage + prop. Tax", ""],
["tblHouse", "House Insurance", ""],
["tblHouse", "furniture", ""],
["", "", ""],
["tblSubscriptions", "YouTube Music", ""],
["tblSubscriptions", "Audible", ""],
["tblSubscriptions", "Disney+", ""],
["tblSubscriptions", "Amazon Prime", ""],
["tblSubscriptions", "costco membership", ""],
["tblSubscriptions", "Microsoft Office", ""],
["tblSubscriptions", "1Password", ""],
["", "", ""],
["tblFood", "Fast Food", ""],
["tblFood", "Groceries", ""],
["tblFood", "Dining Out", ""],
["tblFood", "Energy Drinks/Snacks", ""],
["", "", ""],
["tblClothing", "Gary Clothing", ""],
["tblClothing", "Christina Clothing", ""],
["tblClothing", "Child Clothing", ""],
["tblClothing", "Dry Cleaning", ""],
["tblClothing", "costumes", ""],
["", "", ""],
["tblGrooming", "Beauty Products (soap, makeup, etc.)", ""],
["tblGrooming", "Cleansing Products (shampoo, body wash, etc)", ""],
["tblGrooming", "Teeth (toothbrush, toothpaste, etc)", ""],
["tblGrooming", "Hair Cuts", ""],
["", "", ""],
["tblSupplies", "Cleaning Supplies", ""],
["tblSupplies", "Garden Supplies", ""],
["tblSupplies", "Home Décor", ""],
["tblSupplies", "Organization", ""],
["tblSupplies", "General House Items", ""],
["tblSupplies", "Tools", ""],
["tblSupplies", "Gifts", ""],
["tblSupplies", "Electronics", ""],
["", "", ""],
["tblHealth", "Dental", ""],
["tblHealth", "OTC Drugs", ""],
["tblHealth", "Prescriptions", ""],
["tblHealth", "Supplements", ""],
["tblHealth", "Paramedical", ""],
["tblHealth", "Family Life Insurance", ""],
["tblHealth", "other", ""],
["tblHealth", "Therapy", ""],
["tblHealth", "Sexual Health", ""],
["tblHealth", "Fitness", ""],
["tblHealth", "Feminine Products", ""],
["", "", ""],
["tblBarney", "Preventitive Medical (vaccines, tick, etc)", ""],
["tblBarney", "Emergency Medical", ""],
["tblBarney", "Food", ""],
["tblBarney", "Treats", ""],
["tblBarney", "Toys", ""],
["tblBarney", "Daycare", ""],
["tblBarney", "Pet Insurance (trupanion)", ""],
["tblBarney", "grooming", ""],
["", "", ""],
["tblChildren", "Childcare", ""],
["tblChildren", "ExtraCurriculars", ""],
["tblChildren", "Equipment", ""],
["tblChildren", "Family Activities", ""],
["tblChildren", "Babysitting", ""],
["tblChildren", "Diapers etc (wipes, genie)", ""],
["tblChildren", "Toys", ""],
["tblChildren", "baby supplies", ""],
["", "", ""],
["tblSports", "Friday/Tuesday Hockey", ""],
["tblSports", "AHG Hockey", ""],
["tblSports", "Hockey Equipment", ""],
["tblSports", "Pick-up Hockey", ""],
["", "", ""],
["tblEntertainment", "Books", ""],
["tblEntertainment", "Lottery", ""],
["tblEntertainment", "Dates", ""],
["tblEntertainment", "Concerts/Events", ""],
["tblEntertainment", "Substances", ""],
["tblEntertainment", "Hosting", ""],
["tblEntertainment", "Games", ""],
["", "", ""],
["tblVacations", "Air Fare/public trans.", ""],
["tblVacations", "Accommodations", ""],
["tblVacations", "Alcohol", ""],
["tblVacations", "Food", ""],
["tblVacations", "Travel Insurance", ""],
["tblVacations", "Souvenirs", ""],
["tblVacations", "Rental Car", ""],
["tblVacations", "Other", ""],
["tblVacations", "gas", ""],
["tblVacations", "Camping supplies", ""],
["tblVacations", "Activities", ""],
["", "", ""],
["tblTransportation", "Car cleaning", ""],
["tblTransportation", "Gas/Fuel", ""],
["tblTransportation", "Combined Car Insurance", ""],
["tblTransportation", "Parking", ""],
["tblTransportation", "Tolls", ""],
["tblTransportation", "Licenses Renewals", ""],
["tblTransportation", "Vehicle Maintenance", ""],
["tblTransportation", "Vehicle Registration", ""],
["tblTransportation", "Repairs", ""],
["tblTransportation", "Vehicle inspections", ""],
["tblTransportation", "Public Transport", ""],
["tblTransportation", "Car Payment", ""],
["", "", ""],
["tblDebt", "Student Loans", ""],
["tblDebt", "Solar Loan", ""],
["tblDebt", "Charitable Donations", ""],
["", "", ""],
["tblSavings", "RESP", ""],
["tblSavings", "Christina TFSA", ""],
["tblSavings", "Christina RRSP", ""],
["tblSavings", "Gary TFSA", ""],
["tblSavings", "Gary RRSP", ""],
["tblSavings", "Emerg. Fund", ""],
["tblSavings", "Business Investment", ""],
["", "", ""],
["tblAccounts", "Christina Bank Fees", ""],
["tblAccounts", "Gary Bank Fees", ""],
["tblAccounts", "Mutual Bank Fees", ""],
["tblAccounts", "Accounting", ""],
["", "", ""],
["tblChristinaIncome", "IWK", ""],
["tblChristinaIncome", "Taxable", ""],
["tblChristinaIncome", "Non-Taxable", ""],
["tblGaryIncome", "JTEKT", ""],
["tblGaryIncome", "Taxable", ""],
["tblGaryIncome", "Non-Taxable", ""] ]
